NoteManager/Models/Note.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NoteManager.tools;

namespace NoteManager.Models;

public partial class Note:ISoftDeletable
{
    [Key]
    public int Id { get; set; }

    [Unicode(false)]
    public string? Title { get; set; }

    [Unicode(false)]
    public string? Content { get; set; }

    [Column(TypeName = "image")]
    public byte[]? AttachedImage { get; set; }

    [Column("OwnerID")]
    public string OwnerId { get; set; } = "";


    public bool IsDeleted { get; set; }
}

NoteManager/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NoteManager.Models;
using NoteManager.Models.Requests;
using NoteManager.tools;

namespace NoteManager.Controllers
{
    [Authorize]
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NotesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId

            return View(await _context.Notes.Where((note)=>note.OwnerId== userId).ToListAsync());
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Notes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // GET: Notes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( NoteRequest noteReq)
        {
            Note note = new Note();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            note.OwnerId = userId;
            if (ModelState.IsValid)
            {
                note.Title=noteReq.Title;
                note.Content=noteReq.Content;
                if(noteReq.AttachedImage!=null)
                    note.ImagePath = FileService.Instance.SaveFile(@"uploads\notes-images", noteReq.AttachedImage);
                _context.Add(note);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(note);
        }

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Notes.FindAsync(id);
            if (note == null)
            {
                return NotFound();
            }

            return View(new NoteRequest() { Id=note.Id, Content=note.Content, Title=note.Title});
        }

        // POST: Notes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, NoteRequest noteReq)
        {
            Note note = await _context.Notes.FindAsync(id);

            if (note ==null)
            {
                return NotFound();
            }

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId
            note.OwnerId = userId;

            if (ModelState.IsValid)
            {
                try
                {
                    if (noteReq.AttachedImage != null)
                    {

                        string? oldPath = note.ImagePath;
                        note.ImagePath = FileService.Instance.SaveFile(@"uploads\notes-images", noteReq.AttachedImage);
                        FileService.Instance.DeleteFileAsync(oldPath);
                    }

                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Notes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var note = await _context.Notes.FindAsync(id);
            string? imgPath=null;
            if (note != null)
            {
                imgPath = note.ImagePath;
                _context.Notes.Remove(note);
            }

            await _context.SaveChangesAsync();
            if(imgPath != null)
                FileService.Instance.DeleteFileAsync(imgPath);

            return RedirectToAction(nameof(Index));
        }

        private bool NoteExists(int id)
        {
            return _context.Notes.Any(e => e.Id == id);
        }
    }
}

NoteManager/Controllers/PublicLinksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NoteManager.Models;
using NoteManager.Models.ViewModels;

namespace NoteManager.Controllers
{
    //[Route("PublicLinks")]
    [Authorize]
    public class PublicLinksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PublicLinksController(ApplicationDbContext context)
        {
            _context = context;
        }

        string creataLink(int noteId)
        {
            //string linkStr = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}/";
            string linkStr = $"{this.Request.Scheme}://{this.Request.Host}/PublicLinks/NoteDetails/";
            linkStr += noteId + "";
            return linkStr;
        }


        // GET: PublicLinks
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.PublicLink.Include(p => p.NoteObj);
            
            var x=await applicationDbContext.Include(p=>p.NoteObj).Select((l) => new PublicLinkIndexModel {linkId=l.Id, link = "", noteTitle=l.NoteObj.Title }).ToListAsync();
            foreach (var item in x)
            {
                item.link = creataLink((int)item.linkId);
            }
            return View(x); 

        }

        // GET: PublicLinks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publicLink = await _context.PublicLink
                .Include(p => p.NoteObj)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publicLink == null)
            {
                return NotFound();
            }

            ViewData["linkStr"] =creataLink((int)id);

            return View();
        }

        // GET: PublicLinks/Create/id
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">Note Id</param>
        /// <returns></returns>
        public async Task<IActionResult> Create(int? id)
        {
            if(id == null)
                return BadRequest("note id is required");
            var link = new PublicLink() { Note = (int)id };
            Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry<PublicLink> x = _context.Add(link);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = link.Id });
        }



        // GET: PublicLinks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publicLinks = await _context.PublicLink
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publicLinks == null)
            {
                return NotFound();
            }

            return View(publicLinks);
        }


        // POST: PublicLinks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var publicLink = await _context.PublicLink.FindAsync(id);
            if (publicLink != null)
            {
                _context.PublicLink.Remove(publicLink);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // GET: PublicLinks/NoteDetails/5
        [AllowAnonymous]
        public async Task<IActionResult> NoteDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publicLink = await _context.PublicLink
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publicLink == null)
            {
                return NotFound();
            }

            var note = await _context.Notes
                .FirstOrDefaultAsync(m => m.Id == publicLink.Note);
            if (note == null)
            {
                return NotFound();
            }

            return View("NoteDetails", note);
        }



        private bool PublicLinkExists(int id)
        {
            return _context.PublicLink.Any(e => e.Id == id);
        }
    }
}

NoteManager/Controllers/api/Notes_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NoteManager.Models;
using NoteManager.Models.Responses;

namespace NoteManager.Controllers.api
{
    [Route("api/[controller]")]
    [ApiController]
    public class Notes_Controller : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public Notes_Controller(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Notes_
        [HttpGet]
        public async Task<ActionResult<IEnumerable<NoteResponseModel>>> GetNotes()
        {
            return await _context.Notes.Select((note) => new NoteResponseModel (note)).ToListAsync();
        }

        // GET: api/Notes_/5
        [HttpGet("{id}")]
        public async Task<ActionResult<NoteResponseModel>> GetNote(int id)
        {
            var note = await _context.Notes.FindAsync(id);

            if (note == null)
            {
                return NotFound();
            }

            return new NoteResponseModel(note);
        }

        // PUT: api/Notes_/5
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPut("{id}")]
        public async Task<IActionResult> PutNote(int id, Note note)
        {
            if (id != note.Id)
            {
                return BadRequest();
            }

            _context.Entry(note).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!NoteExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Notes_
        // To protect from overposting attacks, see https://go.microsoft.com/fwlink/?linkid=2123754
        [HttpPost]
        public async Task<ActionResult<NoteResponseModel>> PostNote(Note note)
        {
            _context.Notes.Add(note);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetNote", new { id = note.Id }, new NoteResponseModel(note));
        }

        // DELETE: api/Notes_/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteNote(int id)
        {
            var note = await _context.Notes.FindAsync(id);
            if (note == null)
            {
                return NotFound();
            }

            _context.Notes.Remove(note);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private bool NoteExists(int id)
        {
            return _context.Notes.Any(e => e.Id == id);
        }
    }
}

NoteManager/Views/Notes/Create.cshtml
@using NoteManager.Models.Requests
@model NoteRequest

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AttachedImage" class="control-label"></label>
                <input type="file" asp-for="AttachedImage" name="AttachedImage" multiple="multiple" class="form-control" />
                <span asp-validation-for="AttachedImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NoteManager/Views/Notes/Delete.cshtml
@model NoteManager.Models.Note

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
@*             
        @Html.DisplayNameFor(model => model.AttachedImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AttachedImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerId) 
        </dd>
            *@
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NoteManager/Views/Notes/Details.cshtml
@model NoteManager.Models.Note

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Action("note-image", "Images")/@Model.Id" />
        </dd>

@* 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AttachedImage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AttachedImage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OwnerId)
        </dd>
 *@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

NoteManager/Views/Notes/Edit.cshtml
@using NoteManager.Models.Requests
@model NoteRequest

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AttachedImage" class="control-label"></label>
                <input type="file" asp-for="AttachedImage" class="form-control" />
                <span asp-validation-for="AttachedImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NoteManager/Views/Notes/Index.cshtml
@model IEnumerable<NoteManager.Models.Note>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.AttachedImage) *@
            </th>
            <th>
                @* @Html.DisplayNameFor(model => model.OwnerId) *@
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                    <a asp-controller="PublicLinks" asp-action="Create" asp-route-id="@item.Id">Share</a>
            </td>
@*             <td>
                @Html.DisplayFor(modelItem => item.AttachedImage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerId)
            </td> *@
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>